name: "update protocol"
description: "add the new protocol .zenodo.json and NEWS.md in github.com/inbo/protocolsource"
inputs:
  PAT:
    description: >
      Personal access token (PAT) used to fetch the repository. The PAT is configured
      with the local git config, which enables your scripts to run authenticated git
      commands. The post-job step removes the PAT.


      We recommend using a service account with the least permissions necessary.
      Also when generating a new PAT, select the least scopes necessary.


      [Learn more about creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
    default: ${{ github.token }}
  GITHUB_HEAD_REF:
    description: >
      The name of the protocol branch that is to be merged.
    default: ${{ github.event.pull_request.head.ref }}
  ZENODO:
    description: >
      Token used to create a new Zenodo deposit or update an existing Zenodo
      deposit (https://zenodo.org/).
      The associated DOI will be added or updated in the YAML front matter of
      the protocol's index.Rmd file.
    default: ""
runs:
  using: 'docker'
  image: docker://inbobmk/protocols
  entrypoint: '/entrypoint_update.sh'
  env:
    GITHUB_PAT: ${{ inputs.PAT }}
    GITHUB_HEAD_REF: ${{ inputs.GITHUB_HEAD_REF }}
    ZENODO: ${{ inputs.ZENODO }}
