name: "Elaborate package check"
description: "Thouroughly check an R package on different topics"
inputs:
  path:
    description: >
      Which path must be checked. This path is relative to the root of the repository.
    default: "."
  aptget:
    description: >
      A list of apt-get packages to install. They should be space separated.
    default: ""

runs:
  using: 'docker'
  image: docker://inbobmk/checklist:v0.3.6
  args:
    - ${{ inputs.path }}
    - ${{ inputs.aptget }}
