name: "Render quarto document in a repository"
description: "Render quarto document in a repository"
inputs:
  path:
    description: >
      Path which contains the quarto document.
      This path is relative to the root of the repository.
    default: "."
  output:
    description: >
      Path where the rendered document will be stored.
      This path is relative to the root of the repository.
    default: ""
  extra_repositories:
    description: >
      Additional repositories to use.
      A space separated list of URLs.
      For example: "https://inbo.r-universe.dev https://cranhaven.r-universe.dev"
    default: "https://cranhaven.r-universe.dev https://inbo.r-universe.dev"
  texlive:
    description: >
      Additional TeX Live packages to install.
      A space separated list of package names.
      For example: "babel-dutch babel-french babel-german"
    default: ""
  cmd:
    description: >
      Which commands to run in a bash terminal before installing R dependencies.
      This can be used to set up the environment or install additional dependencies which are not available in a CRAN like repository.
      For example, to install a system library and a package from GitHub:
        sudo apt-get install -y libsodium-dev
        Rscript -e 'pak::pkg_install("jeroen/sodium")'
    default: ""
runs:
  using: "composite"

  steps:

    - name: "Check out code"
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10

    - name: "Check for renv.lock"
      id: check-renv
      run: |
        if [ -f "${{ inputs.path }}/renv.lock" ]; then
          echo "has_renv=true" >> $GITHUB_OUTPUT
        else
          echo "has_renv=false" >> $GITHUB_OUTPUT
        fi
        if [ -n "${{ inputs.apt }}" ]; then
          sudo apt update
          sudo apt install -y ${{ inputs.apt }}
          sudo apt clean
        fi
      shell: bash

    - name: "Set up R"
      uses: r-lib/actions/setup-r@ff9d3a3fd8acec17e91f1d0a1876d95ad60cb519
      with:
        r-version: ${{ steps.check-renv.outputs.has_renv == 'true' && 'renv' || 'release' }}
        extra-repositories: ${{ inputs.extra_repositories }}

    - name: "Set up Pandoc"
      uses: r-lib/actions/setup-pandoc@f50f115c574d8cb2ddc24934af6bed478382b0e7

    - name: Setup Quarto
      uses: quarto-dev/quarto-actions/setup@10ecffe43941bc1d1ea080631818c4aa70ee0435

    - name: Install Quarto dependencies
      run: |
        quarto install tool tinytex --no-prompt --update-path
        tlmgr update --self
        tlmgr install ${{ inputs.texlive }}

        # Install bundled Calibri fonts (repo source of truth)
        sudo mkdir -p /usr/local/share/fonts/truetype/calibri
        sudo cp _extensions/flandersqmd-book/fonts/calibri*.ttf /usr/local/share/fonts/truetype/calibri/

        # Install Inconsolata
        mkdir -p ${HOME}/.fonts
        wget -O ${HOME}/.fonts/Inconsolatazi4-Regular.otf http://mirrors.ctan.org/fonts/inconsolata/opentype/Inconsolatazi4-Regular.otf
        wget -O ${HOME}/.fonts/Inconsolatazi4-Bold.otf http://mirrors.ctan.org/fonts/inconsolata/opentype/Inconsolatazi4-Bold.otf

        # Rebuild cache and verify fonts
        sudo fc-cache -f -v
      shell: bash {0}

    - name: "Run custom commands"
      if: inputs.cmd != ''
      run: ${{ inputs.cmd }}
      shell: bash

    - name: "Install dependencies"
      run: |
        setwd("${{ inputs.path }}")
        if (file.exists("renv.lock")) {
          cat("Restoring the R packages in renv.lock...\n")
          install.packages("renv")
          renv::restore()
        } else {
          install.packages(c("covr", "curl", "cyclocomp", "pak", "pkgdown", "renv"))
          pak::pkg_install("inbo/citeme")
          pak::pkg_install("inbo/checklist")
          citeme::get_default_org_list()
          missing_package <- checklist:::list_missing_packages()
          if (length(missing_package) > 0) {
            cat("Installing missing packages...\n")
            install.packages(missing_package)
          }
        }
      shell: Rscript {0}
      env:
        GITHUB_PAT: ${{ github.token }}
        R_DOWNLOAD_FILE_METHOD: libcurl

    - name: Render Quarto Project
      uses: quarto-dev/quarto-actions/render@87b35bb88b36317fa36b5189e9553b4164a5c5a3
      with:
        path: ${{ inputs.path }}

    - name: "Upload docs artifact"
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
      with:
        name: output
        path: ${{ inputs.output }}
        if-no-files-found: warn
        retention-days: 1
        overwrite: true
