name: "Render quarto document in a repository"
description: "Render quarto document in a repository"
inputs:
  path:
    description: >
      Path which contains the quarto document.
      This path is relative to the root of the repository.
    default: "."
  output:
    description: >
      Path where the rendered document will be stored.
      This path is relative to the root of the repository.
    default: ""
  extra_repositories:
    description: >
      Additional repositories to use.
      A space separated list of URLs.
      For example: "https://inbo.r-universe.dev https://cranhaven.r-universe.dev"
    default: "https://cranhaven.r-universe.dev https://inbo.r-universe.dev"
  extra-packages:
    description: Any extra packages to install outside of the packages listed in the dependencies.
    default: ""
  texlive:
    description: >
      Additional TeX Live packages to install.
      A space or newline separated list of package names.
      For example: "babel-dutch babel-french babel-german"
      Or as a multiline list:
        babel-dutch
        babel-french
        babel-german
    default: ""
  cmd:
    description: >
      Which commands to run in a bash terminal before installing R dependencies.
      This can be used to set up the environment or install additional dependencies which are not available in a CRAN like repository.
      For example, to install a system library and a package from GitHub:
        sudo apt-get install -y libsodium-dev
        Rscript -e 'pak::pkg_install("jeroen/sodium")'
    default: ""
runs:
  using: "composite"

  steps:

    - name: "Check out code"
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10

    - name: "Check for renv.lock"
      id: check-renv
      run: |
        if [ -f "${{ inputs.path }}/renv.lock" ]; then
          echo "has_renv=true" >> $GITHUB_OUTPUT
        else
          echo "has_renv=false" >> $GITHUB_OUTPUT
        fi
        if [ -n "${{ inputs.apt }}" ]; then
          sudo apt update
          sudo apt install -y ${{ inputs.apt }}
          sudo apt clean
        fi
      shell: bash

    - name: "Set up R"
      uses: r-lib/actions/setup-r@ff9d3a3fd8acec17e91f1d0a1876d95ad60cb519
      with:
        r-version: ${{ steps.check-renv.outputs.has_renv == 'true' && 'renv' || 'release' }}
        extra-repositories: ${{ inputs.extra_repositories }}

    - name: "Set up R dependencies"
      uses: r-lib/actions/setup-r-dependencies@2e3959d284a9ed60162f28a0f9891d1150f47f72
      with:
        extra-packages: ${{ inputs.extra-packages }}

    - name: "Set up Pandoc"
      uses: r-lib/actions/setup-pandoc@f50f115c574d8cb2ddc24934af6bed478382b0e7

    - name: Setup Quarto
      uses: quarto-dev/quarto-actions/setup@10ecffe43941bc1d1ea080631818c4aa70ee0435

    - name: Install Quarto dependencies
      run: |
        quarto install tool tinytex --no-prompt --update-path
        tlmgr update --self
        tlmgr option repository https://mirror.ctan.org/systems/texlive/tlnet
        TEXLIVE_PKGS=$(echo "${{ inputs.texlive }}" | tr '\n' ' ' | xargs)
        if [ -n "${TEXLIVE_PKGS}" ]; then
          tlmgr install ${TEXLIVE_PKGS}
        fi
      shell: bash {0}

    - name: "Run custom commands"
      if: inputs.cmd != ''
      run: ${{ inputs.cmd }}
      shell: bash

    - name: Render Quarto Project
      uses: quarto-dev/quarto-actions/render@87b35bb88b36317fa36b5189e9553b4164a5c5a3
      with:
        path: ${{ inputs.path }}

    - name: "Upload docs artifact"
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
      with:
        name: output
        path: ${{ inputs.output }}
        if-no-files-found: warn
        retention-days: 1
        overwrite: true
