name: "Elaborate checks for an R project repository"
description: "Automatically run the required checks on an R project."
inputs:
  repository:
    description: 'Repository name with owner. For example, actions/checkout'
    default: ${{ github.repository }}
  path:
    description: >
      Which path must be checked. This path is relative to the root of the repository.
    default: "."

runs:
  using: 'docker'
  image: docker://inbobmk/checklist:dev-token
  entrypoint: '/entrypoint_project.sh'
  args:
    - ${{ inputs.repository }}
    - ${{ inputs.path }}
