name: "Elaborate checks for an R project repository"
description: "Automatically run the required checks on an R project."
inputs:
  path:
    description: >
      Which path must be checked. This path is relative to the root of the repository.
    default: "."
  extra_repositories:
    description: >
      Additional repositories to use. A space or comma separated list of URLs.
      For example: "https://inbo.r-universe.dev https://cranhaven.r-universe.dev"
    default: "https://cranhaven.r-universe.dev https://inbo.r-universe.dev"

runs:

  using: "composite"
  steps:

    - name: "Check out code"
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10

    - name: "Check for renv.lock"
      id: check-renv
      run: |
        if [ -f "${{ inputs.path }}/renv.lock" ]; then
          echo "has_renv=true" >> $GITHUB_OUTPUT
        else
          echo "has_renv=false" >> $GITHUB_OUTPUT
        fi
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev
      shell: bash

    - name: "Set up R"
      uses: r-lib/actions/setup-r@ff9d3a3fd8acec17e91f1d0a1876d95ad60cb519
      with:
        r-version: ${{ steps.check-renv.outputs.has_renv == 'true' && 'renv' || 'release' }}
        extra-repositories: ${{ inputs.extra_repositories }}

    - name: "Set up Pandoc"
      uses: r-lib/actions/setup-pandoc@f50f115c574d8cb2ddc24934af6bed478382b0e7

    - name: "Setup checklist"
      run: |
        setwd("${{ inputs.path }}")
        options(repos = c("https://cloud.r-project.org", "https://cranhaven.r-universe.dev", "https://inbo.r-universe.dev"))
        cat("Installing checklist and its dependencies...\n")
        install.packages("pak")
        pak::pkg_install(
          c(
            "covr", "curl", "cyclocomp", "jsonlite", "pkgdown", "renv",
            "inbo/citeme", "inbo/checklist@0.5.4"
          )
        )
        cat("Using checklist to install dependencies with pak...\n")
        checklist::install_pak()
      shell: Rscript --no-init-file {0}
      env:
        GITHUB_PAT: ${{ github.token }}
        R_DOWNLOAD_FILE_METHOD: libcurl


    - name: Restore renv library
      if: steps.check-renv.outputs.has_renv == 'true'
      run: |
        setwd("${{ inputs.path }}")
        cat("Installing system requirements for the R packages in renv.lock...\n")
        lock_file <- jsonlite::read_json("renv.lock", simplifyVector = FALSE)$Packages
        cat("Found the following R packages in renv.lock:", paste(names(lock_file), collapse = ", "), "\n")
        names(lock_file) |>
          lapply(
            function(pkg) {
              sysreq <- tryCatch(
                pak::pkg_sysreqs(pkg, upgrade = FALSE),
                error = function(e) {
                  NULL
                }
              )
              sysreq$packages$system_packages
            }
          ) |>
          unlist(use.names = FALSE) |>
          unique() |>
          paste(collapse = " ") |>
          sprintf(fmt = "sudo apt-get install -y %s") -> cmd
        cat("Running command: ", cmd, "\n")
        system(cmd)
        cat("Restoring the R packages in renv.lock...\n")
        renv::restore()
      shell: Rscript {0}
      env:
        GITHUB_PAT: ${{ github.token }}
        R_DOWNLOAD_FILE_METHOD: libcurl

    - name: "Check R Project"
      run: |
        setwd("${{ inputs.path }}")
        version <- tryCatch(
          packageVersion("checklist"),
          error = function(e) {
            if (length(grep("there is no package called", e$message)) == 0) {
              stop(e)
            }
            cat("Installing checklist and its dependencies...\n")
            install.packages("pak")
            pak::pkg_install(
              c(
                "covr", "curl", "cyclocomp", "pkgdown", "renv",
                "inbo/checklist", "inbo/checklist@0.5.4"
              )
            )
            packageVersion("checklist")
          }
        )
        cat("Using checklist version:", as.character(version), "\n")
        if (version >= as.package_version("0.5.0")) {
          if (version >= as.package_version("0.6.0")) {
            cat("Using citeme to get the default org list...\n")
            citeme::get_default_org_list()
          } else {
            cat("Using checklist to get the default org list...\n")
            checklist::get_default_org_list()
          }
          missing_package <- checklist:::list_missing_packages()
          cat("Missing packages: ", paste(missing_package, collapse = ", "), "\n")
          if (length(missing_package) > 0) {
            cat("Installing missing packages...\n")
            pak::pkg_install(missing_package)
          }
        }
        cat("Running checklist::check_project()...\n")
        checklist::check_project(fail = TRUE, quiet = FALSE)
      shell: Rscript {0}
      env:
        GITHUB_PAT: ${{ github.token }}
        R_DOWNLOAD_FILE_METHOD: libcurl
