name: "Render indicatoren"
description: "Render github.com/inbo/indicatoren"
inputs:
  publish:
    description: >
      Publish the indicators. 0 for test render only. 1 for render and publish. Note that 0 implies checking out $GITHUB_SHA$. Whereas 1 implies checking out master.
    default: 0
runs:
  using: 'docker'
  image: docker://inbobmk/indicatoren
  args:
    - ${{ inputs.publish }}
